# Generated by Django 4.2 on 2023-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_products_avgrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='avgrat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
