# Generated by Django 4.2 on 2023-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_avgrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='custname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
