# Generated by Django 4.2 on 2023-04-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_ratings_custname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='custid',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
